apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: ${{values.deployment_name}}-database
spec:
  instances: 1
  imageName: quay.io/enterprisedb/postgresql:14.2
  enableSuperuserAccess: false

  bootstrap:
    initdb:
      database: ${{values.deployment_name}}

  storage:
    size: 1Gi

  resources:
    limits:
      memory: "128Mi"
      cpu: "400m"