{{- if not (eq .Values.environment "dev") -}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ${{values.user}}-${{values.deployment_name}}-pusher-edit
  namespace: "{{ .Values.namespace.name }}"
subjects:
  - kind: ServiceAccount
    name: ${{values.user}}-${{values.deployment_name}}-image-pusher
    namespace: ${{values.component_id}}-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
{{- end }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
#  name: ${{values.user}}-{{ .Values.namespace.name }}
  name: ${{values.deployment_name}}-edit
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: ${{values.user}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
