{{- if not (eq .Values.environment "prod") -}}
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: ${{values.deployment_name}}-database
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    {{- include "quarkus-template-database.labels" . | nindent 4 }}
spec:
  instances: 1
  imageName: quay.io/enterprisedb/postgresql:16.4
  enableSuperuserAccess: false

  bootstrap:
    initdb:
      database: ${{values.deployment_name}}
      postInitApplicationSQLRefs:
        configMapRefs:
        - name: ${{values.deployment_name}}-importsql
          key: import.sql

  storage:
    size: 1Gi

  resources:
    limits:
      memory: "128Mi"
      cpu: "400m"
{{- else }}
kind: Secret
apiVersion: v1
metadata:
  name: ${{values.deployment_name}-database-app
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    {{- include "quarkus-template-database.labels" . | nindent 4 }}
stringData:
  port: 5432
  dbname: ${{values.deployment_name}}
  username: app_user
  jdbc-uri: jdbc:postgresql://${{values.deployment_name}-database-rw.edb-workshop-prod:5432/${{values.deployment_name}?password=DevZone2024#&user=${{values.deployment_name}
type: kubernetes.io/basic-auth
{{- end }}