apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.deployment_name}}-database
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
    {{- include "quarkus-template-database.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ${{values.deployment_name}}-database
  template:
    metadata:
      labels:
        name: ${{values.deployment_name}}-database
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: ${{values.deployment_name}}-database-config
          image: quay.io/rh_ee_slallema/postgres:14
          name: ${{values.deployment_name}}-database
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 32Mi
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: ${{values.deployment_name}}-database
  name: ${{values.deployment_name}}-database-config
stringData:
  POSTGRES_DATABASE: ${{values.deployment_name}}
data:
  POSTGRES_USERNAME: aGVybw==
  POSTGRES_PASSWORD: aGVybw==
  PGDATA: L3RtcC9kYXRh
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ${{values.deployment_name}}-database
  name: ${{values.deployment_name}}-database
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: ${{values.deployment_name}}-database
  type: ClusterIP