apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: fight-ui
  title: Deploy Fight-UI service
  tags:
    - trucathon
    - opencodequest
spec:
  owner: rhdh
  type: service

  parameters:
    - title: Provide information about the OpenShift cluster
      required:
        - openshiftCluster
      properties:
        openshiftCluster:
          title: OpenShift Clusters
          type: string
          enum:
            - cluster-rw97m.sandbox266.opentlc.com
            - cluster-XXXXX.sandboxYYY.opentlc.com

    # - title: Provide information about the GitLab location
    #   required:
    #     - gitlabGroup
    #   properties:
    #     gitlabGroup:
    #       title: Repo Owner
    #       type: string
    #       description: GitLab Organization
    #     description:
    #       title: Description
    #       type: string
    #       description: Help others understand what this component is for
    #       default: Angular SPA for Points-of-Interest Map
    # - title: Provide information about the new component
    #   required:
    #     - namespace
    #   properties:
    #     namespace:
    #       title: Namespace
    #       type: string
    #       description: Namespace
    #       default: poi
  
    - title: Provide Build Information
      required:
        - image_host
        - image_tag
      properties:
        image_host:
          title: Image Host
          type: string
          description: Host for storing image (defaults to openshift internal)
          default: image-registry.openshift-image-registry.svc:5000
        image_tag:
          title: Image Tag
          default: latest
          type: string
          description: Image tag to use for storing in the internal registry

  steps:
    - id: templateSource
      name: Generating the source code component
      action: fetch:template
      input:
        url: ./skeleton
        targetPath: ./source
        values:
          git_host: gitlab-gitlab.apps.${{parameters.openshiftCluster}}
          gitlabGroup: ${{parameters.gitlabGroup}}
          repoName: ${{parameters.namespace}}-frontend
          owner: ${{user.entity.metadata.name}}
          cluster_id: .apps.${{parameters.openshiftCluster}}
          namespace: ${{parameters.namespace}}
          component_id: ${{parameters.namespace}}-poi-map-app
    - id: publishSource
      name: Publishing to Source Code Repository
      action: publish:gitlab
      input:
        sourcePath: ./source
        description: ${{parameters.description}}
        repoUrl: gitlab-gitlab.apps.${{parameters.openshiftCluster}}?owner=${{parameters.gitlabGroup}}&repo=${{parameters.namespace}}-frontend
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: registerSource
      name: Registering the Source Code Component
      action: catalog:register
      input:
        repoContentsUrl: ${{steps.publishSource.output.repoContentsUrl}}
        catalogInfoPath: /catalog-info.yaml
    - id: templateGitops
      name: Generating the deployment resources and artefacts
      action: fetch:template
      input:
        url: ./manifests
        copyWithoutTemplating: []
        values:
          git_host: gitlab-gitlab.apps.${{parameters.openshiftCluster}}
          component_id: ${{parameters.namespace}}-poi-map-app
          description: ${{parameters.description}}
          destination: https://gitlab-gitlab.apps.${{parameters.openshiftCluster}}/${{parameters.gitlabGroup}}/${{parameters.namespace}}-frontend-gitops.git
          source_repository: https://gitlab-gitlab.apps.${{parameters.openshiftCluster}}/${{parameters.gitlabGroup}}/${{parameters.namespace}}-frontend.git
          repository_name: ${{parameters.namespace}}-frontend
          git_owner: ${{parameters.gitlabGroup}}
          cluster: .apps.${{parameters.openshiftCluster}}
          namespace: ${{parameters.namespace}}
          image_host: ${{parameters.image_host}}
          image_name: ${{parameters.namespace}}/poi-map-app
          image_tag: ${{parameters.image_tag}}
        targetPath: ./tenant-gitops
    - id: publishGitops
      name: Publishing to Deployment Resource Repository
      action: publish:gitlab
      input:
        repoUrl: gitlab-gitlab.apps.${{parameters.openshiftCluster}}?owner=${{parameters.gitlabGroup}}&repo=${{parameters.namespace}}-frontend-gitops
        title: gitops resources for ${{parameters.namespace}}-poi-map-app
        description: gitops resources for ${{parameters.namespace}}-poi-map-app
        sourcePath: ./tenant-gitops
        defaultBranch: main
        protectDefaultBranch: false
        repoVisibility: public
    - id: createArgoResources
      name: Create ArgoCD Resources
      action: argocd:create-resources
      input:
        appName: ${{parameters.namespace}}-poi-map-app-bootstrap
        argoInstance: main
        namespace: janus-argocd
        repoUrl: https://gitlab-gitlab.apps.${{parameters.openshiftCluster}}/${{parameters.gitlabGroup}}/${{parameters.namespace}}-frontend-gitops.git
        path: 'argocd/'
  output:
    links:
      - title: Source Code Repository
        url: ${{steps.publishSource.output.remoteUrl}}
      - title: Pipeline status
        url: https://console-openshift-console.apps.${{parameters.openshiftCluster}}/dev-pipelines/ns/${{parameters.namespace}}/
      - title: Open Component in catalog
        icon: catalog
        entityRef: ${{steps.registerSource.output.entityRef}}

